// <auto-generated />
using FootballMatches.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballMatches.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241123213130_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FootballMatches.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiId")
                        .HasColumnType("INT");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)");

                    b.Property<decimal?>("AwayWin")
                        .HasColumnType("DECIMAL (19, 4)");

                    b.Property<long>("Date")
                        .HasColumnType("DATETIMEOFFSET (7)");

                    b.Property<decimal?>("Draw")
                        .HasColumnType("DECIMAL (19, 4)");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(256)");

                    b.Property<decimal?>("HomeWin")
                        .HasColumnType("DECIMAL (19, 4)");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)");

                    b.HasKey("Id");

                    b.ToTable("Match", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
